<?php
	if($this->params['json']){
		echo json_encode($this->params);
		return ;
	}
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>GeText : texte généré</title>
</head>
<body>
<h1>GeText : texte généré</h1>
<?php
	echo "<h2>Paramètres</h2>";
	foreach ($this->params as $k => $v) {
		if($k!="texte")
			echo "<h3>".$k." = ".$v."</h3>";
	}
	echo "<h2>Le texte généré :</h2>";
	echo "<p>".$this->params['texte']."</p>";
	
	?>
</body>
</html>	
