<html>
<head>
    <title>GeText de Sophie Roche</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <script type="text/javascript" src="../../public/js/jquery-1.9.1.js" ></script>
    <script type="text/javascript" src="../../public/js/queue.v1.min.js" ></script>
    <script type="text/javascript" src="../../public/js/d3.v3.js" ></script>
	<style type="text/css">
	html {
	    height: 100%;
	}
	body {
		height:100%;
	    margin: 0;
	    padding: 0;
		background-color:white;
	}
	.page-table {
	    height: 100%;
	    width: 100%;
	    border-collapse: collapse;
	    text-align: center;
	}
	.page-td {
	    height: 100%;
	    padding: 0;
	    vertical-align: middle;
	}
	div.global {
	    width: 168px;
	    margin: 20px auto;
	    text-align: left;
	}
	@font-face { 
	          font-family: Quicksand-Regular; 
	          src: url(../../public/font/quicksand-regular-webfont.ttf) format("truetype");
	     }
	#txtGene {
		position:absolute;
		width:300px;
		height:280px;
		margin-top:120px;
		margin-left:20px;
		overflow: scroll;
		background-color:white;
		font-family: Quicksand-Regular;
 	   background: -webkit-gradient(linear, left top, left bottom, from(#000), to(#045FB4));
    	-webkit-background-clip: text;
    	-webkit-text-fill-color: transparent;
				
		}
		
	#rangeContainer{
		width:160px;
		position:absolute;
		margin-top:350px;
		margin-left:78px;
		padding:0;
	}
	#out{
		display:none;
	}
	input[type='range'] {
		-webkit-appearance: none !important;
		margin:0;
		height:15px;
		width: 160px;
	}
	input[type='range']::-webkit-slider-thumb {
		-webkit-appearance: none !important;
		background:#ececec;
		height:15px;
		width:5px;
	}			
	</style>
    <script type="text/javascript">
		var idPoeme = <?php echo $this->idPoeme; ?>;
		var poeme = <?php echo json_encode($this->poeme); ?>;
    	var toChoix;
	    var paramsGen;
	    var paramsEle = [
	         {titre:"JOYEUX", idBtn:'circle2097',eInfo:null ,eSlt:null, info:'g5156', slt:'g4410', "btnG":'path4346', "lienG":'pJoyeuxG', "btnD":'path4408', "lienD":'pJoyeuxD', couleur:"#f9f569"}
	    	,{titre:"SENTIMENT", idBtn:'circle2101',eInfo:null ,eSlt:null, info:'g5560', slt:'g4410', lien:'pJoyeuxG', lienD:'pJoyeuxD'}
	    	,{titre:"COLERIQUE", idBtn:'circle2105',eInfo:null ,eSlt:null, info:'g5568', slt:'g4579',  "btnG":'path4564', "lienG":'path4560', "btnD":'path4568', "lienD":'path4566', couleur:"#f8533d"}
	    	
	    	];
	    var paramsSelect = {"G":{},"D":{}}
	    var svgChoix;
	    var btnGen;
	    var txtAffect;
	    var tweet;
	    var yLine=300, xLine=70;
		var large = 200, haut = 150;
	    var lineAffect = [{nom:"joyeux", interpolate:"basis", freq:"10", minY:yLine, maxY:30+yLine, couleur:"#FFFF00"}
	        ,{nom:"colérique", interpolate:"linear", freq:"100", minY:yLine, maxY:40+yLine, couleur:"#F993A9"}
	        ,{nom:"calme", interpolate:"basis", freq:"3", minY:-2+yLine, maxY:2+yLine, couleur:"#DD0A0A"}
	        ,{nom:"froid", interpolate:"basis", freq:"6", minY:0+yLine, maxY:20+yLine, couleur:"#E7C5EA"}
	        ,{nom:"sentimental", interpolate:"basis", freq:"50", minY:0+yLine, maxY:40+yLine, couleur:"#3B5A85"}
	        ,{nom:"mélancolique", interpolate:"bundle", freq:"10", minY:0+yLine, maxY:20+yLine, couleur:"#A8E5F6"}
        ];
		var sltAfct = "basis";
		//fonction qui transforme un tableau de données en ligne
		var lineFunction = d3.svg.line()
			.x(function(d) { return d.x; })
			.y(function(d) { return d.y; })
			.interpolate(sltAfct);

	    
		//merci à http://stackoverflow.com/questions/3163615/how-to-scroll-html-page-to-given-anchor-using-jquery-or-javascript
    	function scrollTo(hash) {
	        location.hash = "#" + hash;
	        clearInterval(toChoix);
	    }

	    //charge le premier svg
	    //merci à http://bl.ocks.org/KoGor/8162640
	    function charge(){
	    	queue()
	    		.defer(d3.xml, "../../recherches%20graphiques/nvl_version_getext_sophie/SVG/page2.svg", "image/svg+xml")
	    		.await(charge1);
	    }
	    function charge1(error, xml){
	    	//Adding our svg file to HTML document
			var importedNode = document.importNode(xml.documentElement, true);
    	  	d3.select("#contSvg1").node().appendChild(importedNode);

    	  	//ajoute la définition des dégradés
	    	svgChoix = d3.select("#svgChoix");
			var lineDefs = svgChoix.append("defs");	
			var lineGradient = lineDefs.append("linearGradient")
				.attr("id","MyGradient");
			var color1 = lineGradient.append("stop")
				.attr("id","first")
				.attr("offset","35%")
				.attr("stop-color","#fff");
			var color2 = lineGradient.append("stop")
				.attr("id","second")
				.attr("offset","55%")
				.attr("stop-color","#000");
    	  	
	    	//The data for our line
	    	var afct = lineAffect[2];
	    	var lineData = getAleaData(afct.freq, afct.minY, afct.maxY);
	    	//The line SVG Path we draw
	    	var lineGraph = svgChoix.append("path")
	           .attr("class", "line")
	           .attr("d", lineFunction(lineData))
	           .attr("stroke", "url(#MyGradient)")
	           .attr("stroke-width", 2)
	           .attr("fill", "none");
	               	  	
			//charge le deuxième svg
	    	queue()
	    		.defer(d3.xml, "../../recherches%20graphiques/nvl_version_getext_sophie/SVG/page4.svg", "image/svg+xml")
    			.await(charge2);
	    }

	    function charge2(error, xml){
	    	//Adding our svg file to HTML document
			var importedNode = document.importNode(xml.documentElement, true);
    	  	d3.select("#contSvg2").node().appendChild(importedNode);
    	  	init();
	    }
	    
	    function init(){
		    
			//attend 3 secondes avant d'afficher la suite
			if(idPoeme){
				$('#txtGene').html(poeme[0].texte);
		    	toChoix=setInterval(function(){scrollTo("texte")},3000);
			}else
		    	toChoix=setInterval(function(){scrollTo("choix")},3000);

	    	//ajoute les événements aux boutons
	    	btnGen = document.getElementById("g3104"); 
	    	btnGen.addEventListener("click", genTexte, false);
	    	btnGen.setAttribute("visibility","hidden");
	    		    	
	    	var btnGoChoix = document.getElementById("g9237"); 
	    	btnGoChoix.addEventListener("click", function(){scrollTo("choix")}, false);
	    	
	    	/* 
	    	var btnSave = document.getElementById("circle5062"); 
	    	btnSave.addEventListener("click", saveTexte, false); 
			*/
	    	var btnTweet = document.getElementById("path5542"); 
	    	btnTweet.addEventListener("click", envoiTweet, false); 

	    	//ajoute les événements aux paramètres
	    	paramsEle.forEach(ajoutInterParams);

	    	//récupère les textes de sélection
	    	paramsSelect["D"].txt = d3.select("#txtDroite");
	    	paramsSelect["G"].txt = d3.select("#txtGauche");
	    	
	    }
	    
	    function ajoutInterParams(e, i){
		    //ajoute le click sur le cercle
	    	var cb = document.getElementById(e.idBtn);
	    	cb.addEventListener("click", showParam, false);
			//ajoute l'attribut idParam pour récupérer directement les données liées
    		cb.setAttribute("idParam", i);
		    //ajoute le click sur le btnG
	    	var bG = document.getElementById(e.btnG);
	    	if(bG){
		    	bG.addEventListener("click", animeSelect, false);
				//ajoute l'attribut idParam pour récupérer directement les données liées
	    		bG.setAttribute("idParam", i);
	    	}
		    //ajoute le click sur le btnD
	    	var bD = document.getElementById(e.btnD);
	    	if(bD){
		    	bD.addEventListener("click", animeSelect, false);
				//ajoute l'attribut idParam pour récupérer directement les données liées
	    		bD.setAttribute("idParam", i);
	    	}
			//masque l'info
	    	var g = document.getElementById(e.info);
	    	g.setAttribute("visibility","hidden");	    	
			//conserve l'élément d'information 
	    	e.eInfo = g;
			//conserve l'élément de selection 
	    	e.eSlt = document.getElementById(e.slt);
	    }
	    function showParam(evt){
		    //récupère le paramètre de donnée
	    	var e = evt.currentTarget;
	    	var idP = e.getAttribute("idParam");
	    	//affiche ou masque les boutons suivant la sélection
	    	//		    	if(i==idP && (txtG.innerHTML==paramsEle[i].titre || txtG.innerHTML==paramsEle[i].titre)){
	    	paramsEle.forEach(function(d, i){
		    	if(i==idP){
			    	paramsEle[i].eInfo.setAttribute("visibility","visible");	    		    	
		    	}else{
			    	paramsEle[i].eInfo.setAttribute("visibility","hidden");	    		    	
		    	}			    	
	    	});	    	
	    }

	    function animeSelect(evt){

			//récupère le paramètre de donnée
		    var e = evt.currentTarget;
			var idP = e.getAttribute("idParam");
			
			//récupère le chemin d'animation
	    	var dir="D";
	    	if(paramsEle[idP]["btnG"]==e.id) dir="G";

	    	//spécifie la sélection
			setSelect(idP, dir)

			//effectue la transition sur le chemin
	    	transitionMarker(paramsSelect[dir].marker, paramsSelect[dir].path);
	    	
	    }	    

	    function setSelect(idP, dir){
	    	paramsSelect[dir].path = svgChoix.select("#"+paramsEle[idP]["lien"+dir]);
	    	paramsSelect[dir].path.attr("idParam", idP); 
			//enregistre l'ancien marker s'il existe
	    	if(paramsSelect[dir].marker) paramsSelect[dir].markerOld = paramsSelect[dir].marker;
			//récupère le point de départ
	    	var startPoint = pathStartPoint(paramsSelect[dir].path);
			//construction du marker
			var marker = svgChoix.append("circle");
	    	marker.attr("r", 6)
	    	    .attr("idParam", idP)
	    	    .attr("dir", dir)
	    	    .attr("style", "fill:"+paramsEle[idP].couleur)
	    	    .attr("transform", "translate(" + startPoint + ")");
	    	paramsSelect[dir].marker = marker; 
	    }
	    
  	  	//Get path start point for placing marker
		function pathStartPoint(path) {
  	    	var d = path.attr("d"),
  	    	dsplitted = d.split(" ");
  	    	return dsplitted[1].split(",");
  	  	}

  	  	function transitionMarker(marker, path) {
  	    	marker.transition()
  	        	.duration(6000)
  	        	.attrTween("transform", translateAlong(path.node()))
  	        	.each("end", endSelect);// infinite loop
  	  	}
  	  	function translateAlong(path) {
  	    	var l = path.getTotalLength();
      		return function(i) {
        		return function(t) {
	          		var p = path.getPointAtLength(t * l);
    	      		return "translate(" + p.x + "," + p.y + ")";//Move marker
        		}
      		}
  	  	}	    	
	    function endSelect(){
		    //récupère le paramètre de donnée
	    	var idP = this.getAttribute("idParam");
			var dir = this.getAttribute("dir");
	    	//masque les boutons de selection
			paramsEle[idP].eSlt.setAttribute("visibility","hidden");	    		    	
			paramsEle[idP].eInfo.setAttribute("visibility","hidden");
			paramsSelect[dir].txt.text(paramsEle[idP].titre)
					.attr("idParam",idP)
	    	    	.style("fill", paramsEle[idP].couleur)
				;
			//affiche la sélection du marker précédent s'il existe
			if(paramsSelect[dir].markerOld){
				paramsEle[paramsSelect[dir].markerOld.attr("idParam")].eSlt.setAttribute("visibility","visible");
				//supprime le vieux marker
				paramsSelect[dir].markerOld.remove();	    		    	
			}	    		    	

			//vérifie s'il faut afficher le bouton
	    	if(paramsSelect["G"].marker && paramsSelect["D"].marker)
		    	btnGen.setAttribute("visibility","visible");	    	

			//montre l'onde
	    	animeOnde();

	    	//calcul le dégradé
	    	gradient();
			
	    }

	    function gradient(){
	    	
			//Récupération de la valeur du input "range"

			var grad = document.getElementById('out').value;
			var grad1 = 2-grad;
			var x = -5;
			
			//Couleurs 1 et 2 par défaut (blanc)
			var couleur1 = '#fff';
			var couleur2 = '#fff';
			
			//récupère les couleurs
			if(paramsSelect["G"].path){
				couleur1 = paramsEle[paramsSelect["G"].path.attr("idParam")].couleur;
			}
			if(paramsSelect["D"].path){
				couleur2 = paramsEle[paramsSelect["D"].path.attr("idParam")].couleur;
			}
			
			gradientFond(couleur1, couleur2);

			//Dégradé de la courbe
			var color1 = document.getElementById("first");
				color1.setAttribute('offset', grad1*-1 + '%');
				color1.setAttribute('stop-color', couleur1);
			var color2 = document.getElementById("second");
				color2.setAttribute('offset', grad - x + '%');
				color2.setAttribute('stop-color', couleur2);

		};
			    
		//Dégradé d'arrière plan du input "range"		
		function gradientFond(couleur1, couleur2){
		
			var prct = getPrctGrad();
		
			var test = document.getElementById('rangeContainer');
			test.style.background="linear-gradient(90deg, " + couleur1 + " " + prct.a + "%, " + couleur2 + " " + prct.b + "%)";
		}

		//Dégradé récupère le pourcentage des couleurs		
		function getPrctGrad(){
			var grad2 = document.getElementById('out').value;
			var grad2Neg = grad2*-1;
		
			var a = grad2-30;
			var b = 30-grad2Neg;
			
			return {"a":a,"b":b}
		}
		
		function transitionPath(path, d0, d1) {
			  path.transition()
			      .duration(2000)
			      .attrTween("d", pathTween(d1, 4));
			      //.each("end", function() { d3.select(this).call(transition, d1, d0); });
			}

		function pathTween(d1, precision) {
		  return function() {
		    var path0 = this,
		        path1 = path0.cloneNode(),
		        n0 = path0.getTotalLength(),
		        n1 = (path1.setAttribute("d", d1), path1).getTotalLength();

		    // Uniform sampling of distance based on specified precision.
		    var distances = [0], i = 0, dt = precision / Math.max(n0, n1);
		    while ((i += dt) < 1) distances.push(i);
		    distances.push(1);

		    // Compute point-interpolators at each distance.
		    var points = distances.map(function(t) {
		      var p0 = path0.getPointAtLength(t * n0),
		          p1 = path1.getPointAtLength(t * n1);
		      return d3.interpolate([p0.x, p0.y], [p1.x, p1.y]);
		    });

		    return function(t) {
		      return t < 1 ? "M" + points.map(function(p) { return p(t); }).join("L") : d1;
		    };
		  };
		}

		function animeOnde(){
			//récupère les paramètre de l'affection
			var afct = lineAffect[Math.floor((5)*Math.random())];
			console.log(afct.nom);
			//précise l'interpolation sélectionnée
			sltAfct = afct.interpolate;
			//calcule les données de la ligne
			var data = getAleaData(afct.freq, afct.minY, afct.maxY);
			//calcule les coordonnées de la ligne avec les paramètre de l'affection
			var d1 = lineFunction(data);
			//récupère les coordonnés de la ligne initiale
			var path = d3.select(".line");
			var d0 = path.attr("d");
			//affiche la transition entre les deux lignes
			transitionPath(path, d0, d1);
		}
		function animeReset(){
			d3.select(".line").transition()
		       .duration(3000)
		       .attr("d", lineFunction([{"x":0, "y":0},{"x":400, "y":0}]))
		       .each("end", anime);
		}

		function getAleaData(freq, minY, maxY){
			var data = [];
			var pas = large/freq;
			for (var i=0;i<freq;i++)
			{ 
				var y =  Math.floor((maxY-minY)*Math.random())+minY; 
				data.push({ "x": xLine+(pas*i),   "y": y});
			}	
			return data;
		}	    
	    function genTexte(){
			var p = getParamGen();
		    $.getJSON('../api/gettext', p, 
				function(fragment){
			    	$('#txtGene').html(fragment.texte);
			    	scrollTo("texte");
			    });
	    }
	    function saveTexte(){
			$.post("../api/savetext"
				, getParamsSave(),
				 function(data){
					idPoeme=data;
				 });
	    }

	    function getParamsSave(){
			var p = {"texte":$('#txtGene').html(),"params":getParamGen()};
	    	return p;	    	 
	    }
	    function getParamGen(){
		    //récupère les identifiants d'affects sélectionnés
		    var idPg = paramsSelect["G"].marker.attr("idParam");
		    var idPd = paramsSelect["D"].marker.attr("idParam");
		    //récupère les affects
		    var affG = paramsEle[idPg].titre;
		    var affD = paramsEle[idPd].titre;
		    //récupère les pourcentages
		    var prct = getPrctGrad();
		    //construction des paramètres
		    var p = {'json':1,'pro':'propositions/sophie'};
		    p[affG] = prct.a; 
		    p[affD] = prct.b; 
	    	return p; 
	    }
		function envoiTweet() {
			$.post("../api/savetext"
			, getParamsSave(),
			 function(data){
				idPoeme=data.idP;
				var poeme = $('#txtGene').text();
				poeme = poeme.substr(0,100)+"... ";
				var tweet = "#GeText "+poeme+data.urlCourte;
			   	window.open('https://twitter.com/intent/tweet?text=' + encodeURIComponent(tweet),
			       '',
			       'status=no, scrollbars=no, menubar=no');				
			 }, "json");			
		}
	    
	</script>
  </head>
  <body onload="charge()">
	<table id="accueil" class="page-table"><tr><td class="page-td">
	    <div id="global" style="background-color:black;">
			<div style="text-align:center;" onclick="scrollTo('choix')">
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   version="1.1"
   width="336"
   height="476"
   id="svg8900">
  <defs
     id="defs8902">
    <linearGradient
       x1="133.8633"
       y1="324.8613"
       x2="218.0625"
       y2="324.8613"
       id="SVGID_320_"
       gradientUnits="userSpaceOnUse">
      <stop
         id="stop5413"
         style="stop-color:#a9eff7;stop-opacity:1"
         offset="0.29949999" />
      <stop
         id="stop5415"
         style="stop-color:#fcb4ce;stop-opacity:1"
         offset="0.89999998" />
    </linearGradient>
    <linearGradient
       x1="133.8633"
       y1="324.8613"
       x2="218.0625"
       y2="324.8613"
       id="SVGID_321_"
       gradientUnits="userSpaceOnUse">
      <stop
         id="stop5420"
         style="stop-color:#a9eff7;stop-opacity:1"
         offset="0.29949999" />
      <stop
         id="stop5422"
         style="stop-color:#fcb4ce;stop-opacity:1"
         offset="0.89999998" />
    </linearGradient>
    <linearGradient
       x1="182"
       y1="327.5"
       x2="205"
       y2="327.5"
       id="SVGID_322_"
       gradientUnits="userSpaceOnUse">
      <stop
         id="stop5427"
         style="stop-color:#cad8e7;stop-opacity:1"
         offset="0" />
      <stop
         id="stop5429"
         style="stop-color:#ced5e5;stop-opacity:1"
         offset="0.2449" />
      <stop
         id="stop5431"
         style="stop-color:#dccbde;stop-opacity:1"
         offset="0.51340002" />
      <stop
         id="stop5433"
         style="stop-color:#f1bcd3;stop-opacity:1"
         offset="0.792" />
      <stop
         id="stop5435"
         style="stop-color:#fcb4ce;stop-opacity:1"
         offset="0.89999998" />
    </linearGradient>
  </defs>
  <metadata
     id="metadata8905">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title></dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <g
     transform="translate(0,-576.36218)"
     id="layer1">
    <rect
       width="332.50107"
       height="472.54703"
       x="2.5601017"
       y="579.27246"
       id="rect2075"
       style="fill:#ffffff" />
    <rect
       width="332.50107"
       height="472.54703"
       x="1.3680161"
       y="576.85608"
       id="rect4432"
       style="fill:none" />
    <text
       x="1.3317897"
       y="602.93359"
       transform="scale(1.0273528,0.97337542)"
       id="text4434"
       style="font-size:22.06693268px;opacity:0.5">
      <tspan
         x="1.3317897"
         y="602.93359"
         id="tspan4436"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Contrairement</tspan>
      <tspan
         x="109.7411"
         y="602.93359"
         id="tspan4438"
         style="font-size:14.71128941px;letter-spacing:1.83891118;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="117.43514"
         y="602.93359"
         id="tspan4440"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">à</tspan>
      <tspan
         x="125.87939"
         y="602.93359"
         id="tspan4442"
         style="font-size:14.71128941px;letter-spacing:1.83891118;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="133.57158"
         y="602.93359"
         id="tspan4444"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">une</tspan>
      <tspan
         x="160.56863"
         y="602.93359"
         id="tspan4446"
         style="font-size:14.71128941px;letter-spacing:1.83891118;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="168.25711"
         y="602.93359"
         id="tspan4448"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">opinion</tspan>
      <tspan
         x="222.66127"
         y="602.93359"
         id="tspan4450"
         style="font-size:14.71128941px;letter-spacing:1.83891118;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="230.35347"
         y="602.93359"
         id="tspan4452"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">répandue,</tspan>
      <tspan
         x="304.67673"
         y="602.93359"
         id="tspan4454"
         style="font-size:14.71128941px;letter-spacing:1.83891118;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="312.36707"
         y="602.93359"
         id="tspan4456"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">le</tspan>
      <tspan
         x="1.3317897"
         y="625.83344"
         id="tspan4458"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Lorem</tspan>
      <tspan
         x="48.216667"
         y="625.83344"
         id="tspan4460"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="53.124702"
         y="625.83344"
         id="tspan4462"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Ipsum</tspan>
      <tspan
         x="97.567528"
         y="625.83344"
         id="tspan4464"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="102.47559"
         y="625.83344"
         id="tspan4466"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">n'est</tspan>
      <tspan
         x="136.95882"
         y="625.83344"
         id="tspan4468"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="141.86688"
         y="625.83344"
         id="tspan4470"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">pas</tspan>
      <tspan
         x="167.92058"
         y="625.83344"
         id="tspan4472"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="172.82864"
         y="625.83344"
         id="tspan4474"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">simplement</tspan>
      <tspan
         x="258.37296"
         y="625.83344"
         id="tspan4476"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="263.28098"
         y="625.83344"
         id="tspan4478"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">du</tspan>
      <tspan
         x="282.01025"
         y="625.83344"
         id="tspan4480"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="286.91647"
         y="625.83344"
         id="tspan4482"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">texte</tspan>
      <tspan
         x="1.3317897"
         y="648.73163"
         id="tspan4484"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">aléatoire.</tspan>
      <tspan
         x="70.180595"
         y="648.73163"
         id="tspan4486"
         style="font-size:14.71128941px;letter-spacing:5.51673317;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="80.138321"
         y="648.73163"
         id="tspan4488"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Il</tspan>
      <tspan
         x="88.288391"
         y="648.73163"
         id="tspan4490"
         style="font-size:14.71128941px;letter-spacing:5.51673317;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="98.251617"
         y="648.73163"
         id="tspan4492"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">trouve</tspan>
      <tspan
         x="146.32993"
         y="648.73163"
         id="tspan4494"
         style="font-size:14.71128941px;letter-spacing:5.51673317;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="156.29129"
         y="648.73163"
         id="tspan4496"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">ses</tspan>
      <tspan
         x="179.72456"
         y="648.73163"
         id="tspan4498"
         style="font-size:14.71128941px;letter-spacing:5.51673317;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="189.68227"
         y="648.73163"
         id="tspan4500"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">racines</tspan>
      <tspan
         x="242.99597"
         y="648.73163"
         id="tspan4502"
         style="font-size:14.71128941px;letter-spacing:5.51673317;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="252.9592"
         y="648.73163"
         id="tspan4504"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">dans</tspan>
      <tspan
         x="288.03088"
         y="648.73163"
         id="tspan4506"
         style="font-size:14.71128941px;letter-spacing:5.51673317;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="297.99225"
         y="648.73163"
         id="tspan4508"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">une</tspan>
      <tspan
         x="1.3317897"
         y="671.63159"
         id="tspan4510"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">oeuvre</tspan>
      <tspan
         x="52.482925"
         y="671.63159"
         id="tspan4512"
         style="font-size:14.71128941px;letter-spacing:5.51673317;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="64.171051"
         y="671.63159"
         id="tspan4514"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">de</tspan>
      <tspan
         x="82.839676"
         y="671.63159"
         id="tspan4516"
         style="font-size:14.71128941px;letter-spacing:5.51673317;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="94.527832"
         y="671.63159"
         id="tspan4518"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">la</tspan>
      <tspan
         x="107.29723"
         y="671.63159"
         id="tspan4520"
         style="font-size:14.71128941px;letter-spacing:5.51673317;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="118.97982"
         y="671.63159"
         id="tspan4522"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">littérature</tspan>
      <tspan
         x="193.38948"
         y="671.63159"
         id="tspan4524"
         style="font-size:14.71128941px;letter-spacing:5.51673317;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="205.07758"
         y="671.63159"
         id="tspan4526"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">latine</tspan>
      <tspan
         x="245.84442"
         y="671.63159"
         id="tspan4528"
         style="font-size:14.71128941px;letter-spacing:5.51673317;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="257.52515"
         y="671.63159"
         id="tspan4530"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">classique</tspan>
      <tspan
         x="1.3317897"
         y="694.53156"
         id="tspan4532"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">datant</tspan>
      <tspan
         x="50.042698"
         y="694.53156"
         id="tspan4534"
         style="font-size:14.71128941px;letter-spacing:1.83891118;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="56.519348"
         y="694.53156"
         id="tspan4536"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">de</tspan>
      <tspan
         x="75.187965"
         y="694.53156"
         id="tspan4538"
         style="font-size:14.71128941px;letter-spacing:1.83891118;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="81.668297"
         y="694.53156"
         id="tspan4540"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">45</tspan>
      <tspan
         x="100.33509"
         y="694.53156"
         id="tspan4542"
         style="font-size:14.71128941px;letter-spacing:1.83891118;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="106.80989"
         y="694.53156"
         id="tspan4544"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">av.</tspan>
      <tspan
         x="127.86359"
         y="694.53156"
         id="tspan4546"
         style="font-size:14.71128941px;letter-spacing:1.83891118;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="134.33839"
         y="694.53156"
         id="tspan4548"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">J.-C.,</tspan>
      <tspan
         x="170.57045"
         y="694.53156"
         id="tspan4550"
         style="font-size:14.71128941px;letter-spacing:1.83891118;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="177.04895"
         y="694.53156"
         id="tspan4552"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">le</tspan>
      <tspan
         x="189.67122"
         y="694.53156"
         id="tspan4554"
         style="font-size:14.71128941px;letter-spacing:1.83891118;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="196.14786"
         y="694.53156"
         id="tspan4556"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">rendant</tspan>
      <tspan
         x="254.30342"
         y="694.53156"
         id="tspan4558"
         style="font-size:14.71128941px;letter-spacing:1.83891118;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="260.78192"
         y="694.53156"
         id="tspan4560"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">vieux</tspan>
      <tspan
         x="299.84036"
         y="694.53156"
         id="tspan4562"
         style="font-size:14.71128941px;letter-spacing:1.83891118;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="306.32068"
         y="694.53156"
         id="tspan4564"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">de</tspan>
      <tspan
         x="1.3317897"
         y="717.43152"
         id="tspan4566"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">2000</tspan>
      <tspan
         x="41.344658"
         y="717.43152"
         id="tspan4568"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="46.44577"
         y="717.43152"
         id="tspan4570"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">ans.</tspan>
      <tspan
         x="75.191643"
         y="717.43152"
         id="tspan4572"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="80.292793"
         y="717.43152"
         id="tspan4574"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Un</tspan>
      <tspan
         x="101.2858"
         y="717.43152"
         id="tspan4576"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="106.39063"
         y="717.43152"
         id="tspan4578"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">professeur</tspan>
      <tspan
         x="184.94705"
         y="717.43152"
         id="tspan4580"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="190.05003"
         y="717.43152"
         id="tspan4582"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">du</tspan>
      <tspan
         x="208.77933"
         y="717.43152"
         id="tspan4584"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="213.88048"
         y="717.43152"
         id="tspan4586"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Hampden-Syd</tspan>
      <tspan
         x="318.97974"
         y="717.43152"
         id="tspan4588"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">-</tspan>
      <tspan
         x="1.3317897"
         y="740.32971"
         id="tspan4590"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">ney</tspan>
      <tspan
         x="27.959215"
         y="740.32971"
         id="tspan4592"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="32.701756"
         y="740.32971"
         id="tspan4594"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">College,</tspan>
      <tspan
         x="91.576355"
         y="740.32971"
         id="tspan4596"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="96.315224"
         y="740.32971"
         id="tspan4598"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">en</tspan>
      <tspan
         x="114.29427"
         y="740.32971"
         id="tspan4600"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="119.03128"
         y="740.32971"
         id="tspan4602"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Virginie,</tspan>
      <tspan
         x="179.99486"
         y="740.32971"
         id="tspan4604"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="184.7356"
         y="740.32971"
         id="tspan4606"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">s'est</tspan>
      <tspan
         x="217.43878"
         y="740.32971"
         id="tspan4608"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="222.17949"
         y="740.32971"
         id="tspan4610"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">intéressé</tspan>
      <tspan
         x="289.02573"
         y="740.32971"
         id="tspan4612"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="293.76645"
         y="740.32971"
         id="tspan4614"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">à</tspan>
      <tspan
         x="302.21072"
         y="740.32971"
         id="tspan4616"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="306.95145"
         y="740.32971"
         id="tspan4618"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">un</tspan>
      <tspan
         x="1.3317897"
         y="763.22955"
         id="tspan4620"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">des</tspan>
      <tspan
         x="27.238363"
         y="763.22955"
         id="tspan4622"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="30.816883"
         y="763.22955"
         id="tspan4624"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">mots</tspan>
      <tspan
         x="67.122498"
         y="763.22955"
         id="tspan4626"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="70.701019"
         y="763.22955"
         id="tspan4628"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">latins</tspan>
      <tspan
         x="109.74481"
         y="763.22955"
         id="tspan4630"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="113.3233"
         y="763.22955"
         id="tspan4632"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">les</tspan>
      <tspan
         x="133.18356"
         y="763.22955"
         id="tspan4634"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="136.76027"
         y="763.22955"
         id="tspan4636"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">plus</tspan>
      <tspan
         x="166.39058"
         y="763.22955"
         id="tspan4638"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="169.9673"
         y="763.22955"
         id="tspan4640"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">obscurs,</tspan>
      <tspan
         x="230.60724"
         y="763.22955"
         id="tspan4642"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="234.18387"
         y="763.22955"
         id="tspan4644"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">consectetur,</tspan>
      <tspan
         x="1.3317897"
         y="786.12952"
         id="tspan4646"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">extrait</tspan>
      <tspan
         x="50.143826"
         y="786.12952"
         id="tspan4648"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="55.340595"
         y="786.12952"
         id="tspan4650"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">d'un</tspan>
      <tspan
         x="86.471535"
         y="786.12952"
         id="tspan4652"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="91.668304"
         y="786.12952"
         id="tspan4654"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">passage</tspan>
      <tspan
         x="152.73485"
         y="786.12952"
         id="tspan4656"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="157.93166"
         y="786.12952"
         id="tspan4658"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">du</tspan>
      <tspan
         x="176.66095"
         y="786.12952"
         id="tspan4660"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="181.85771"
         y="786.12952"
         id="tspan4662"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Lorem</tspan>
      <tspan
         x="228.74257"
         y="786.12952"
         id="tspan4664"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="233.94115"
         y="786.12952"
         id="tspan4666"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Ipsum,</tspan>
      <tspan
         x="281.76755"
         y="786.12952"
         id="tspan4668"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="286.96616"
         y="786.12952"
         id="tspan4670"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">et</tspan>
      <tspan
         x="301.80981"
         y="786.12952"
         id="tspan4672"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="307.01025"
         y="786.12952"
         id="tspan4674"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">en</tspan>
      <tspan
         x="1.3317897"
         y="809.02948"
         id="tspan4676"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">étudiant</tspan>
      <tspan
         x="63.049316"
         y="809.02948"
         id="tspan4678"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="68.865784"
         y="809.02948"
         id="tspan4680"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">tous</tspan>
      <tspan
         x="100.20086"
         y="809.02948"
         id="tspan4682"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="106.01547"
         y="809.02948"
         id="tspan4684"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">les</tspan>
      <tspan
         x="125.87574"
         y="809.02948"
         id="tspan4686"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="131.6922"
         y="809.02948"
         id="tspan4688"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">usages</tspan>
      <tspan
         x="182.96104"
         y="809.02948"
         id="tspan4690"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="188.77567"
         y="809.02948"
         id="tspan4692"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">de</tspan>
      <tspan
         x="207.44429"
         y="809.02948"
         id="tspan4694"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="213.26262"
         y="809.02948"
         id="tspan4696"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">ce</tspan>
      <tspan
         x="230.62193"
         y="809.02948"
         id="tspan4698"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="236.44026"
         y="809.02948"
         id="tspan4700"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">mot</tspan>
      <tspan
         x="265.50787"
         y="809.02948"
         id="tspan4702"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="271.32254"
         y="809.02948"
         id="tspan4704"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">dans</tspan>
      <tspan
         x="306.39609"
         y="809.02948"
         id="tspan4706"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="312.21442"
         y="809.02948"
         id="tspan4708"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">la</tspan>
      <tspan
         x="1.3317897"
         y="831.92767"
         id="tspan4710"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">littérature</tspan>
      <tspan
         x="75.743317"
         y="831.92767"
         id="tspan4712"
         style="font-size:14.71128941px;letter-spacing:5.51673317;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="87.254898"
         y="831.92767"
         id="tspan4714"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">classique,</tspan>
      <tspan
         x="158.10449"
         y="831.92767"
         id="tspan4716"
         style="font-size:14.71128941px;letter-spacing:5.51673317;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="169.61055"
         y="831.92767"
         id="tspan4718"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">découvrit</tspan>
      <tspan
         x="239.93417"
         y="831.92767"
         id="tspan4720"
         style="font-size:14.71128941px;letter-spacing:5.51673317;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="251.44022"
         y="831.92767"
         id="tspan4722"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">la</tspan>
      <tspan
         x="264.20963"
         y="831.92767"
         id="tspan4724"
         style="font-size:14.71128941px;letter-spacing:5.51673317;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="275.71573"
         y="831.92767"
         id="tspan4726"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">source</tspan>
      <tspan
         x="1.3317897"
         y="854.82764"
         id="tspan4728"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">incontestable</tspan>
      <tspan
         x="100.5043"
         y="854.82764"
         id="tspan4730"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="104.33841"
         y="854.82764"
         id="tspan4732"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">du</tspan>
      <tspan
         x="123.06586"
         y="854.82764"
         id="tspan4734"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="126.89817"
         y="854.82764"
         id="tspan4736"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Lorem</tspan>
      <tspan
         x="173.78304"
         y="854.82764"
         id="tspan4738"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="177.61719"
         y="854.82764"
         id="tspan4740"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Ipsum.</tspan>
      <tspan
         x="225.44354"
         y="854.82764"
         id="tspan4742"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="229.27586"
         y="854.82764"
         id="tspan4744"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Il</tspan>
      <tspan
         x="237.42587"
         y="854.82764"
         id="tspan4746"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="241.26004"
         y="854.82764"
         id="tspan4748"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">provient</tspan>
      <tspan
         x="303.18164"
         y="854.82764"
         id="tspan4750"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="307.01212"
         y="854.82764"
         id="tspan4752"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">en</tspan>
      <tspan
         x="1.3317897"
         y="877.7276"
         id="tspan4754"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">fait</tspan>
      <tspan
         x="25.783785"
         y="877.7276"
         id="tspan4756"
         style="font-size:14.71128941px;letter-spacing:3.67782235;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="34.978336"
         y="877.7276"
         id="tspan4758"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">des</tspan>
      <tspan
         x="60.884914"
         y="877.7276"
         id="tspan4760"
         style="font-size:14.71128941px;letter-spacing:3.67782235;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="70.081322"
         y="877.7276"
         id="tspan4762"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">sections</tspan>
      <tspan
         x="130.14752"
         y="877.7276"
         id="tspan4764"
         style="font-size:14.71128941px;letter-spacing:3.67782235;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="139.34209"
         y="877.7276"
         id="tspan4766"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">1.10.32</tspan>
      <tspan
         x="184.06071"
         y="877.7276"
         id="tspan4768"
         style="font-size:14.71128941px;letter-spacing:3.67782235;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="193.25526"
         y="877.7276"
         id="tspan4770"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">et</tspan>
      <tspan
         x="208.09894"
         y="877.7276"
         id="tspan4772"
         style="font-size:14.71128941px;letter-spacing:3.67782235;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="217.29349"
         y="877.7276"
         id="tspan4774"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">1.10.33</tspan>
      <tspan
         x="262.3082"
         y="877.7276"
         id="tspan4776"
         style="font-size:14.71128941px;letter-spacing:3.67782235;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="271.50461"
         y="877.7276"
         id="tspan4778"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">du</tspan>
      <tspan
         x="290.23206"
         y="877.7276"
         id="tspan4780"
         style="font-size:14.71128941px;letter-spacing:3.67782235;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="299.42474"
         y="877.7276"
         id="tspan4782"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">&quot;De</tspan>
      <tspan
         x="1.3317897"
         y="900.62756"
         id="tspan4784"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Finibus</tspan>
      <tspan
         x="53.483307"
         y="900.62756"
         id="tspan4786"
         style="font-size:14.71128941px;letter-spacing:16.55019951;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="75.495079"
         y="900.62756"
         id="tspan4788"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Bonorum</tspan>
      <tspan
         x="141.10742"
         y="900.62756"
         id="tspan4790"
         style="font-size:14.71128941px;letter-spacing:16.55019951;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="163.12653"
         y="900.62756"
         id="tspan4792"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">et</tspan>
      <tspan
         x="177.97206"
         y="900.62756"
         id="tspan4794"
         style="font-size:14.71128941px;letter-spacing:16.55019951;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="199.99304"
         y="900.62756"
         id="tspan4796"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Malorum&quot;</tspan>
      <tspan
         x="269.8735"
         y="900.62756"
         id="tspan4798"
         style="font-size:14.71128941px;letter-spacing:16.55019951;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="291.88525"
         y="900.62756"
         id="tspan4800"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">(Des</tspan>
      <tspan
         x="1.3317897"
         y="923.52563"
         id="tspan4802"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Suprêmes</tspan>
      <tspan
         x="75.474846"
         y="923.52563"
         id="tspan4804"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="80.90699"
         y="923.52563"
         id="tspan4806"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Biens</tspan>
      <tspan
         x="118.99452"
         y="923.52563"
         id="tspan4808"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="124.42669"
         y="923.52563"
         id="tspan4810"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">et</tspan>
      <tspan
         x="139.27222"
         y="923.52563"
         id="tspan4812"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="144.70802"
         y="923.52563"
         id="tspan4814"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">des</tspan>
      <tspan
         x="170.61455"
         y="923.52563"
         id="tspan4816"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="176.04858"
         y="923.52563"
         id="tspan4818"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Suprêmes</tspan>
      <tspan
         x="250.19162"
         y="923.52563"
         id="tspan4820"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="255.62558"
         y="923.52563"
         id="tspan4822"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Maux)</tspan>
      <tspan
         x="300.8775"
         y="923.52563"
         id="tspan4824"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="306.31152"
         y="923.52563"
         id="tspan4826"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">de</tspan>
      <tspan
         x="1.3317897"
         y="946.42737"
         id="tspan4828"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Cicéron.</tspan>
      <tspan
         x="62.221813"
         y="946.42737"
         id="tspan4830"
         style="font-size:14.71128941px;letter-spacing:12.8723774;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="80.642189"
         y="946.42737"
         id="tspan4832"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Cet</tspan>
      <tspan
         x="106.8283"
         y="946.42737"
         id="tspan4834"
         style="font-size:14.71128941px;letter-spacing:12.8723774;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="125.25601"
         y="946.42737"
         id="tspan4836"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">ouvrage,</tspan>
      <tspan
         x="189.64731"
         y="946.42737"
         id="tspan4838"
         style="font-size:14.71128941px;letter-spacing:12.8723774;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="208.06767"
         y="946.42737"
         id="tspan4840"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">très</tspan>
      <tspan
         x="236.60574"
         y="946.42737"
         id="tspan4842"
         style="font-size:14.71128941px;letter-spacing:12.8723774;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="255.03162"
         y="946.42737"
         id="tspan4844"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">populaire</tspan>
      <tspan
         x="1.3317897"
         y="969.32556"
         id="tspan4846"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">pendant</tspan>
      <tspan
         x="62.740379"
         y="969.32556"
         id="tspan4848"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="68.409729"
         y="969.32556"
         id="tspan4850"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">la</tspan>
      <tspan
         x="81.179138"
         y="969.32556"
         id="tspan4852"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="86.848511"
         y="969.32556"
         id="tspan4854"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Renaissance,</tspan>
      <tspan
         x="180.60355"
         y="969.32556"
         id="tspan4856"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="186.27657"
         y="969.32556"
         id="tspan4858"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">est</tspan>
      <tspan
         x="208.35825"
         y="969.32556"
         id="tspan4860"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="214.02942"
         y="969.32556"
         id="tspan4862"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">un</tspan>
      <tspan
         x="232.06729"
         y="969.32556"
         id="tspan4864"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="237.74037"
         y="969.32556"
         id="tspan4866"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">traité</tspan>
      <tspan
         x="278.16696"
         y="969.32556"
         id="tspan4868"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="283.83817"
         y="969.32556"
         id="tspan4870"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">sur</tspan>
      <tspan
         x="306.5524"
         y="969.32556"
         id="tspan4872"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="312.22363"
         y="969.32556"
         id="tspan4874"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">la</tspan>
      <tspan
         x="1.3317897"
         y="992.22552"
         id="tspan4876"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">théorie</tspan>
      <tspan
         x="53.939358"
         y="992.22552"
         id="tspan4878"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="58.183563"
         y="992.22552"
         id="tspan4880"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">de</tspan>
      <tspan
         x="76.852188"
         y="992.22552"
         id="tspan4882"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="81.100067"
         y="992.22552"
         id="tspan4884"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">l'éthique.</tspan>
      <tspan
         x="147.21448"
         y="992.22552"
         id="tspan4886"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="151.46049"
         y="992.22552"
         id="tspan4888"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Les</tspan>
      <tspan
         x="175.93823"
         y="992.22552"
         id="tspan4890"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="180.18242"
         y="992.22552"
         id="tspan4892"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">premières</tspan>
      <tspan
         x="255.04633"
         y="992.22552"
         id="tspan4894"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="259.29056"
         y="992.22552"
         id="tspan4896"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">lignes</tspan>
      <tspan
         x="302.01398"
         y="992.22552"
         id="tspan4898"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="306.26001"
         y="992.22552"
         id="tspan4900"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">du</tspan>
      <tspan
         x="1.3317897"
         y="1015.1255"
         id="tspan4902"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Lorem</tspan>
      <tspan
         x="48.216667"
         y="1015.1255"
         id="tspan4904"
         style="font-size:14.71128941px;letter-spacing:9.19455528;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="63.510868"
         y="1015.1255"
         id="tspan4906"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Ipsum,</tspan>
      <tspan
         x="111.3373"
         y="1015.1255"
         id="tspan4908"
         style="font-size:14.71128941px;letter-spacing:9.19455528;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="126.63335"
         y="1015.1255"
         id="tspan4910"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">&quot;Lorem</tspan>
      <tspan
         x="179.548"
         y="1015.1255"
         id="tspan4912"
         style="font-size:14.71128941px;letter-spacing:9.19455528;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="194.84225"
         y="1015.1255"
         id="tspan4914"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">ipsum</tspan>
      <tspan
         x="238.93379"
         y="1015.1255"
         id="tspan4916"
         style="font-size:14.71128941px;letter-spacing:9.19455528;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="254.228"
         y="1015.1255"
         id="tspan4918"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">dolor</tspan>
      <tspan
         x="292.44977"
         y="1015.1255"
         id="tspan4920"
         style="font-size:14.71128941px;letter-spacing:9.19455528;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="307.73666"
         y="1015.1255"
         id="tspan4922"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">sit</tspan>
      <tspan
         x="1.3317897"
         y="1038.0236"
         id="tspan4924"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">amet...&quot;,</tspan>
      <tspan
         x="58.838196"
         y="1038.0236"
         id="tspan4926"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="62.920578"
         y="1038.0236"
         id="tspan4928"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">proviennent</tspan>
      <tspan
         x="151.83929"
         y="1038.0236"
         id="tspan4930"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="155.91982"
         y="1038.0236"
         id="tspan4932"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">de</tspan>
      <tspan
         x="174.59033"
         y="1038.0236"
         id="tspan4934"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="178.6727"
         y="1038.0236"
         id="tspan4936"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">la</tspan>
      <tspan
         x="191.44209"
         y="1038.0236"
         id="tspan4938"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="195.52448"
         y="1038.0236"
         id="tspan4940"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">section</tspan>
      <tspan
         x="248.35272"
         y="1038.0236"
         id="tspan4942"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="252.4351"
         y="1038.0236"
         id="tspan4944"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">1.10.32.fait</tspan>
      <tspan
         x="1.3317897"
         y="1060.9235"
         id="tspan4946"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">des</tspan>
      <tspan
         x="27.238363"
         y="1060.9235"
         id="tspan4948"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="32.475567"
         y="1060.9235"
         id="tspan4950"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">sections</tspan>
      <tspan
         x="92.541779"
         y="1060.9235"
         id="tspan4952"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="97.777184"
         y="1060.9235"
         id="tspan4954"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">1.10.32</tspan>
      <tspan
         x="142.49767"
         y="1060.9235"
         id="tspan4956"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="147.73488"
         y="1060.9235"
         id="tspan4958"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">et</tspan>
      <tspan
         x="162.58038"
         y="1060.9235"
         id="tspan4960"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="167.8158"
         y="1060.9235"
         id="tspan4962"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">1.10.33</tspan>
      <tspan
         x="212.83044"
         y="1060.9235"
         id="tspan4964"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="218.06584"
         y="1060.9235"
         id="tspan4966"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">du</tspan>
      <tspan
         x="236.79515"
         y="1060.9235"
         id="tspan4968"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="242.0305"
         y="1060.9235"
         id="tspan4970"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">&quot;De</tspan>
      <tspan
         x="267.59875"
         y="1060.9235"
         id="tspan4972"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular" />
      <tspan
         x="272.83597"
         y="1060.9235"
         id="tspan4974"
         style="font-size:14.71128941px;opacity:0.7;fill:#a9eff7;font-family:Quicksand-Regular">Finibus</tspan>
    </text>
    <rect
       width="204.03474"
       height="29.607578"
       x="65.601173"
       y="868.34955"
       id="rect5126"
       style="fill:none" />
    <text
       x="97.508316"
       y="907.54803"
       transform="scale(1.0273528,0.97337542)"
       id="text5128"
       style="font-size:22.06693268px;letter-spacing:9.19455528;fill:#adacad;font-family:Quicksand-Light">GeText</text>
    <g
       transform="matrix(1.8892106,0,0,1.7899509,-159.912,203.38282)"
       id="g5406">
      <g
         id="g5408">
        <g
           id="g5410">
          <linearGradient
             x1="133.8633"
             y1="324.8613"
             x2="218.0625"
             y2="324.8613"
             id="linearGradient8872"
             gradientUnits="userSpaceOnUse">
            <stop
               id="stop8874"
               style="stop-color:#a9eff7;stop-opacity:1"
               offset="0.29949999" />
            <stop
               id="stop8876"
               style="stop-color:#fcb4ce;stop-opacity:1"
               offset="0.89999998" />
          </linearGradient>
          <path
             d="m 164.039,323.77 h 22.102 v 1.767 c 0,4.019 -0.473,7.576 -1.42,10.67 -0.924,2.864 -2.482,5.542 -4.678,8.037 -4.965,5.589 -11.281,8.384 -18.949,8.384 -7.482,0 -13.893,-2.703 -19.227,-8.107 -5.336,-5.427 -8.004,-11.94 -8.004,-19.539 0,-7.76 2.715,-14.342 8.143,-19.747 5.426,-5.427 12.031,-8.141 19.814,-8.141 4.182,0 8.084,0.851 11.711,2.552 3.463,1.702 6.869,4.465 10.219,8.292 l -5.75,5.508 c -4.389,-5.843 -9.734,-8.765 -16.041,-8.765 -5.658,0 -10.404,1.952 -14.238,5.854 -3.834,3.834 -5.75,8.638 -5.75,14.412 0,5.958 2.137,10.867 6.408,14.723 3.996,3.581 8.326,5.37 12.992,5.37 3.973,0 7.539,-1.336 10.705,-4.008 3.164,-2.695 4.93,-5.92 5.299,-9.676 h -13.336 v -7.586 z"
             id="path5417"
             style="fill:url(#SVGID_320_)" />
          <linearGradient
             x1="133.8633"
             y1="324.8613"
             x2="218.0625"
             y2="324.8613"
             id="linearGradient8879"
             gradientUnits="userSpaceOnUse">
            <stop
               id="stop8881"
               style="stop-color:#a9eff7;stop-opacity:1"
               offset="0.29949999" />
            <stop
               id="stop8883"
               style="stop-color:#fcb4ce;stop-opacity:1"
               offset="0.89999998" />
          </linearGradient>
          <path
             d="m 205.799,305.721 v 45.902 h -8.072 V 305.721 H 185.43 v -7.587 h 32.633 v 7.587 h -12.264 z"
             id="path5424"
             style="fill:url(#SVGID_321_)" />
        </g>
      </g>
      <linearGradient
         x1="182"
         y1="327.5"
         x2="205"
         y2="327.5"
         id="linearGradient8886"
         gradientUnits="userSpaceOnUse">
        <stop
           id="stop8888"
           style="stop-color:#cad8e7;stop-opacity:1"
           offset="0" />
        <stop
           id="stop8890"
           style="stop-color:#ced5e5;stop-opacity:1"
           offset="0.2449" />
        <stop
           id="stop8892"
           style="stop-color:#dccbde;stop-opacity:1"
           offset="0.51340002" />
        <stop
           id="stop8894"
           style="stop-color:#f1bcd3;stop-opacity:1"
           offset="0.792" />
        <stop
           id="stop8896"
           style="stop-color:#fcb4ce;stop-opacity:1"
           offset="0.89999998" />
      </linearGradient>
      <rect
         width="23"
         height="7"
         x="182"
         y="324"
         id="rect5437"
         style="fill:url(#SVGID_322_)" />
      <rect
         width="16"
         height="7"
         x="121"
         y="323"
         id="rect5439"
         style="fill:#a9eff7" />
    </g>
  </g>
</svg>
			</div>
	    </div><!-- #global -->
	</td></tr></table>
	<table id="choix" class="page-table"><tr><td class="page-td">
	    <div class="global" style="background-color:black;">
			<div id="contSvg1" style="text-align:center;">
			<form id="rangeContainer" onsubmit="return false" oninput="out.value = valeur.valueAsNumber; gradient();">
				<input type="range" min="0" max ="100" value="50" id="valeur" name="valeur">
				<output name="out" id="out" for="valeur" >50</output>
			</form>
			

			</div>
	    </div><!-- #global -->
	</td></tr></table>
	<table id="texte" class="page-table"><tr><td class="page-td">
	    <div class="global" style="background-color:red;">
			<div id="contSvg2" style="text-align:center;">
			    <div id="txtGene" ></div>
			</div>
	    </div><!-- #global -->
	</td></tr></table>

  </body>
</html>